FROM node:22-alpine

WORKDIR /app

RUN apk add --no-cache git

COPY frontend/package*.json ./
RUN npm install

COPY frontend/ /app/

EXPOSE 5173

# CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]
